# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0002_user_avater'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avater',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='/static/default.png ', max_length=200, upload_to='avater/%Y/%m', verbose_name='Head_portrait'),
        ),
    ]
