# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='tltle',
            new_name='title',
        ),
    ]
